ALTER TABLE transactions ADD COLUMN IF NOT EXISTS lorry_no VARCHAR(50);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS tons DOUBLE PRECISION;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS rate_per_ton DOUBLE PRECISION;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS other_charges DOUBLE PRECISION DEFAULT 0;
